In [1]:
# Importing required packages
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
from scipy.optimize import fsolve, fminbound

In [2]:
# Quasi-Newton unconstained optimization 
def quasi_newton_opt(x0, func_grad, func_line_search, max_iter=500, full_output=False):
    # Function to perform a quasi-Newton optimization
    # for an unconstrained problem with BFGS Hessian update

    # x0: Inital point
    # func_grad: Gradient of function
    # func_line_search: Objective function with used for line search

    B0 = np.identity(2, dtype=float)    # initializing hessian
    iter_no = 0
    stop = False
    while True:
        delta_f0 = func_grad(x0)    # calculating gradient
        sq = np.dot(-B0, delta_f0)  # calculating search direction
        alpha = fminbound(lambda alpha: func_line_search(x0, alpha, sq), 0, 2)  # line search along sq
        x_new = x0 + alpha * sq # new point
        delta_f_new = func_grad(x_new)  # gradient at new point 

        # Checking for stationary point:
        for delta_f in delta_f_new:
            if abs(delta_f) > 1E-07:
                stop = False
            else:
                stop = True
        if stop or iter_no > max_iter:
            break

        delta_x = x_new - x0    # change in x
        delta_delta = delta_f_new - delta_f0    # change in gradient
        delta_B = BFGS_update(B0, delta_x, delta_delta) # BFGS hessian update

        # Updating values for next iteration
        B_new = B0 + delta_B
        B0 = B_new
        x0 = x_new
        delta_f0 = delta_f_new
        iter_no = iter_no + 1
        
    if full_output:
        return [x_new, delta_f_new, B_new, iter_no]
    return x_new

In [3]:
def func(x):
    # Objective function definition

    # x: Evaluation point
    f = (x[0] + 2*x[1] - 7)**2 + (2*x[0] + x[1] - 5)**2 # Test quadratic function
    return f


def func_grad(x):
    # Function to calculate gradient 
    # of objective function using forward FD

    # x: Evaluation point

    step = 1E-8 # step size for FD
    delta_f = np.zeros((2, 1))
    delta_f[0] = (func(np.array([x[0]+step, x[1]])) - func(x)) / step
    delta_f[1] = (func(np.array([x[0], x[1]+step])) - func(x)) / step
    return delta_f

# def func_grad_test(x):
#     step = 1E-8
#     x_dim = len(x)
#     delta_f = np.zeros((2, 1))
#     for i in range(x_dim):
#         x_new = np.array(x)
#         x_new[i] = x[i] + step
#         delta_f[i] = (func(x_new) - func(x)) / step
#     return delta_f


def func_line_search(x0, alpha, sq):
    # Function for line search

    # x0: Initial point
    # alpha: Scaling parameter
    # sq: Search direction
    
    x_new = x0 + alpha*sq
    return func(x_new)


def BFGS_update(B, delta_x, delta_delta):
    # Function to update to hessian
    # using BFGS method

    # B: initial hessian
    # delta_x: change in evaluation point
    # delta_delta: change in gradient
    
    delta_x_T = delta_x.transpose()
    delta_delta_T = delta_delta.transpose()
    delta_B = (1 + (np.dot(np.dot(delta_delta_T, B), delta_delta))/(np.dot(delta_x_T, delta_delta))) * \
    (np.dot(delta_x, delta_x_T)/np.dot(delta_x_T, delta_delta)) - \
        (np.dot(delta_x, np.dot(delta_delta_T, B)) + np.dot(np.dot(delta_delta_T, B).transpose(), delta_x_T)) / \
            (np.dot(delta_x_T, delta_delta))
    
    return delta_B

In [6]:
x0 = np.array([[0, 0]]).transpose()
[x, delta_f, B, iter_no] = quasi_newton_opt(x0, func_grad, func_line_search, full_output=True)
print(f'Optima: \n{x}\nGradient at optima: \n{delta_f}\nHessian inverse at optima: \n{B}')
print(f'Iterations: {iter_no}')

Optima: 
[[1.]
 [3.]]
Gradient at optima: 
[[4.97392675e-08]
 [5.02383101e-08]]
Hessian inverse at optima: 
[[ 0.27777779 -0.22222223]
 [-0.22222223  0.27777779]]
Iterations: 2
